# Generated by Django 4.1.5 on 2023-01-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
