# Generated by Django 4.1.5 on 2023-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_programs_courselevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselevel',
            name='course',
        ),
        migrations.AddField(
            model_name='courselevel',
            name='course',
            field=models.ManyToManyField(to='main_page.course'),
        ),
    ]
